# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
  };
in
{
  wasm2js = nodeEnv.buildNodePackage {
    name = "wasm2js";
    packageName = "wasm2js";
    version = "0.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/wasm2js/-/wasm2js-0.2.0.tgz";
      sha1 = "4757c3b2cfbfda7bf23822157c293170029df613";
    };
    dependencies = [
      sources."minimist-1.2.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Compile WebAssembly .wasm files to a commonjs module.";
      homepage = https://github.com/thlorenz/wasm2js;
      license = {
        type = "MIT";
        url = "https://github.com/thlorenz/wasm2js/blob/master/LICENSE";
      };
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}